version: "3.8"
services:
  api-cpu: &api-cpu
    image: ghcr.io/nova-ims-innovation-and-analytics-lab/mapintel-api-cpu:latest
    profiles:
      - cpu
    hostname: api
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - odfe-node1
    networks:
      - odfe-net
    secrets:
      - dotenv-file
    volumes:
      - ./artifacts:/home/user/artifacts
  api-gpu:
    <<: *api-cpu
    image: ghcr.io/nova-ims-innovation-and-analytics-lab/mapintel-api-gpu:latest
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: odfe-node1
    environment:
      - node.name=odfe-node1
      - discovery.type=single-node
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - odfe-net
  ui: &ui
    image: ghcr.io/nova-ims-innovation-and-analytics-lab/mapintel-ui:latest
    ports:
      - 8501:8501
    environment:
      - API_ENDPOINT=http://api:8000
    networks:
      - odfe-net
  ui-dev:
    <<: *ui
    profiles:
      - dev
    volumes:
      - ./ui:/home/user/ui

volumes:
  odfe-data1: # empty entries will be created according to the "platform's default configuration"

networks:
  odfe-net:

secrets:
  dotenv-file:
    file: ./.env
