version: '0.8'
# TODO: Pass this yaml when docker-compose up is run so we can pass arbitrary configurations to the app after the images are built

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: CustomOpenDistroElasticsearchDocumentStore
    params:
      host: odfe-node1
      port: 9200
      username: admin    # TODO: the access needs to be more secure before deployment
      password: admin
      scheme: https
      embedding_dim: 768 # Change to 512 when using the sentence-transformers/distiluse-base-multilingual-cased-v1 embedding_model below
      verify_certs: False
      similarity: cosine
      return_embedding: True
  - name: Retriever    # api/controller/feedback.py has this name hard coded. DO NOT CHANGE!
    type: TopicRetriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
      embedding_model: sentence-transformers/msmarco-distilbert-base-v4   # Use sentence-transformers/distiluse-base-multilingual-cased-v1 for Multilingual corpora
      model_format: bertopic
      top_k: 100
  - name: Reader    # custom-name for the component; helpful for visualization & debugging
    type: CrossEncoderReRanker    # Haystack Class name for the component
    params:
      cross_encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
      top_k: 10

pipelines:
  - name: query
    type: Query
    nodes:
      - name: Retriever
        inputs: [Query]
      - name: Reader
        inputs: [Retriever]

  - name: indexing
    type: Indexing
    nodes:
      - name: Retriever
        inputs: [File]
      - name: DocumentStore
        inputs: [Retriever]
